// listeningBank.js - بنك الأسئلة السماعية
window.listeningBank = {
    A1: [
        { id: "A1_01", audio: "audio/level_test/A1 Q01.mp4", text: "How old is Tom?", options: ["Twelve", "Twenty", "Thirty"], correct: "Twenty", transcript: "Woman: Hello. What's your name? Man: My name is Tom. Woman: Nice to meet you, Tom. Man: Nice to meet you too." },
        { id: "A1_02", audio: "audio/level_test/A1 Q02.mp4", text: "Where is the cat?", options: ["On the table", "Under the table", "Behind the door"], correct: "Under the table", transcript: "Man: Where is the cat? Woman: Look, it's under the table. Man: Oh yes, I see it." },
        { id: "A1_03", audio: "audio/level_test/A1 Q03.mp4", text: "How many apples are in the bag?", options: ["One", "Two", "Three"], correct: "Two", transcript: "Woman: What do you have in your bag? Man: I have two apples and a banana. Woman: No sandwich? Man: No, no sandwich today." },
        { id: "A1_04", audio: "audio/level_test/A1 Q04.mp4", text: "Who is at the door?", options: ["Tom's mother", "Tom's sister", "Tom's friend"], correct: "Tom's sister", transcript: "Man: Who is it? Woman: It's Sarah, your sister. Man: Okay, coming." },
        { id: "A1_05", audio: "audio/level_test/A1 Q05.mp4", text: "When is the museum closed?", options: ["On Tuesdays", "On Sundays", "On Mondays"], correct: "On Mondays", transcript: "Woman: Is the museum open today? Man: No, it's closed on Mondays. Come back tomorrow.Woman: Okay, thank you." },
        { id: "A1_06", audio: "audio/level_test/A1 Q06.mp3", text: "What does the boy choose to drink?", options: ["Juice" , "Water" , "Tea" , "Milk"], correct: "Milk", transcript: "Boy: Mum, can I have some juice? Mother: There's no juice. We have water or milk. Boy: Okay, I'll have milk, please." },
        { id: "A1_07", audio: "audio/level_test/A1 Q07.mp3", text: "Where is the library?", options: ["Next to the school", "Next to the post office", "Opposite the park", "Behind the supermarket"], correct: "Next to the post office", transcript: "Woman: Excuse me, where is the library? Man: Go straight, then turn left. It's next to the post office. Woman: Thank you very much." },
        { id: "A1_08", audio: "audio/level_test/A1 Q08.mp3", text: " Which page do the students open to?", options: ["Two", "Twenty", "Twelve", "Thirty"], correct: "Twelve", transcript: "Teacher: Class, open your books to page twelve. Student: Sorry, is that page twelve or twenty? Teacher: Page twelve. One-two." },
        { id: "A1_09", audio: "audio/level_test/A1 Q09.mp3", text: "How much does the coffee cost?", options: ["One pound fifty", "Two pounds", "Two pounds fifty", "Three pounds"], correct: "Two pounds fifty", transcript: "Man: How much is this coffee? Cashier: That's two pounds fifty. Man: Here you go." },
        { id: "A1_10", audio: "audio/level_test/A1 Q10.mp3", text: "What time does the shop close on a normal day?", options: ["Four o'clock", "Five o'clock", "Six o'clock", "Seven o'clock"], correct: " Six o'clock", transcript: "Woman: What time does the shop close? Man: It closes at six o'clock in the evening. Woman: And does it open on Sundays? Man: Yes, but only until two o'clock." },
        { id: "A1_11", audio: "audio/level_test/A1 Q11.mp3", text: "Where were the shoes?", options: ["By the front door", "In the kitchen", "In the wardrobe", "Under the bed"], correct: "Under the bed", transcript: "Girl: Dad, where are my shoes? Father: I think they're by the front door. Girl: No, they're not there. Father: Did you look under your bed? Girl: Oh yes! Found them!" },
        { id: "A1_12", audio: "audio/level_test/A1 Q12.mp3", text: "Where does this bus go?", options: ["To the city centre", "To the train station", "To the airport", "To the hospital"], correct: "To the airport", transcript: "Man: Excuse me. Is this the bus to the city centre? Driver: No, this bus goes to the airport. You need the number seven. Man: Thank you." }
    ],
    A2: [
        { id: "A2_01", audio: "audio/level_test/A2 Q01.mp4", text: "What does the woman order to drink?", options: ["Water", "Orange juice", "Tomato soup"], correct: "Orange juice", transcript: "Waiter: Anything to drink? Man: Just water. Woman: Orange juice for me." },
        { id: "A2_02", audio: "audio/level_test/A2 Q02.mp4", text: "When will the train to Manchester leave?", options: ["At 5:15", "At 5:35", "At 5:50"], correct: "At 5:35", transcript: "The 5:15 train is delayed by 20 minutes. It will depart at 5:35." },
        { id: "A2_03", audio: "audio/level_test/A2 Q03.mp4", text: "What did the man think about the movie?", options: ["It was boring", "It was funny", "It was scary"], correct: "It was funny", transcript: "Man: I watched a movie. It was very funny." },
        { id: "A2_04", audio: "audio/level_test/A2 Q04.mp4", text: "What time is David Miller's appointment?", options: ["Thursday at 10 AM", "Friday at 2 PM", "Friday at 10 AM"], correct: "Friday at 2 PM", transcript: "Receptionist: Friday at 2 PM. Man: I'll take that." },
        { id: "A2_05", audio: "audio/level_test/A2 Q05.mp4", text: "How much does the woman pay for the shirt?", options: ["$30", "$22", "$20"], correct: "$22", transcript: "Shop assistant: It's on sale for $22. Woman: Great, I'll take it." }
    ],
    B1: [
        { id: "B1_01", audio: "audio/level_test/B1 Q01.mp4", text: "What does Anna ask Mark to do?", options: ["Write the report", "Check the numbers on page 5", "Email the report to the boss"], correct: "Check the numbers on page 5", transcript: "Anna: Could you double-check the numbers on page 5?" },
        { id: "B1_02", audio: "audio/level_test/B1 Q02.mp4", text: "Which gate should passengers for Dublin go to?", options: ["Gate 7", "Gate 12", "Gate 20"], correct: "Gate 12", transcript: "Announcer: Passengers for Dublin, proceed to gate 12." },
        { id: "B1_03", audio: "audio/level_test/B1 Q03.mp4", text: "Who is the character Henry based on?", options: ["The author's father", "The author's uncle", "The author's grandfather"], correct: "The author's uncle", transcript: "Author: Henry is based on my uncle." },
        { id: "B1_04", audio: "audio/level_test/B1 Q04.mp4", text: "What will they do in the morning?", options: ["Go to the beach", "Go to the art gallery", "Stay at home"], correct: "Go to the art gallery", transcript: "Lucy: Let's go to the art gallery in the morning." },
        { id: "B1_05", audio: "audio/level_test/B1 Q05.mp4", text: "Why should Mrs. Parker call back?", options: ["Test results abnormal", "Schedule follow-up", "Change office hours"], correct: "Schedule follow-up", transcript: "Please call to schedule a follow-up appointment." }
    ],
    B2: [
        { id: "B2_01", audio: "audio/level_test/B2 Q01.mp4", text: "What is the most effective action for the environment?", options: ["Recycling plastic", "Reducing consumption", "Buying new clothes"], correct: "Reducing consumption", transcript: "Reducing our consumption is even more effective than recycling." },
        { id: "B2_02", audio: "audio/level_test/B2 Q02.mp4", text: "How much will the tourist pay for two student tickets?", options: ["$45", "$70", "$90"], correct: "$70", transcript: "Student ticket is $35 each. Two tickets = $70." },
        { id: "B2_03", audio: "audio/level_test/B2 Q03.mp4", text: "What is the main problem with screen time for older children?", options: ["Causes poor sleep", "Replaces activity and social time", "Exposes to bad content"], correct: "Replaces activity and social time", transcript: "The real problem is when screens replace physical activity and social time." },
        { id: "B2_04", audio: "audio/level_test/B2 Q04.mp4", text: "What advice does the speaker give to newcomers?", options: ["Always look at the map", "Don't use the Tube", "Ask station staff for help"], correct: "Ask station staff for help", transcript: "Don't be afraid to ask station staff for help." },
        { id: "B2_05", audio: "audio/level_test/B2 Q05.mp4", text: "What causes lower customer satisfaction in the afternoons?", options: ["Poor product quality", "Not enough staff", "Bad training"], correct: "Not enough staff", transcript: "We're understaffed between 1 PM and 3 PM." }
    ],
    C1: [], C2: []
};
